Revise cleanup scripts to not require cd
Digilent/Genesys-ZU-HW pull request #1
Opened 2020-04-30 00:46 UTC by artvvb

Detecting and either CDing into or acting only within the directory the cleanup scripts are placed in may help avoid these scripts removing other important parts of a filesystem.

2020-06-23 12:17 UTC, elodg requested changes
Good idea, would make these scripts safer.

2020-06-23 12:17 UTC, elodg commented on proj/cleanup.cmd
> +rem go silent
A simple "pushd %~dp0" would suffice.

2020-06-23 12:17 UTC, elodg commented on proj/cleanup.cmd
> +cd %orig_dir%
"popd"

2020-06-24 18:18 UTC, artvvb commented on proj/cleanup.cmd
> +rem go silent
New commit resolves this

2020-06-24 18:19 UTC, artvvb commented
Returned "@echo off" to first line of file.

2020-07-10 15:28 UTC, elodg approved these changes

2020-07-10 18:09 UTC, merged